name - Fahad Bin Hussain
id - 23101376
section - 5
set - A



In [ ]:
import matplotlib.pyplot as plt
import numpy as np

task1

In [ ]:
import numpy as np

def newton_eval(x_nodes, coeffs, x_val):
    result = coeffs[0]
    product = 1.0
    for i in range(1, len(coeffs)):
        product *= (x_val - x_nodes[i-1])
        result += coeffs[i] * product
    return result

x =[-1.5, 0.5, 1.7]
f =[3.62, 1.22, 2.90]

n = len(x)
dd = np.zeros((n+1, n+1))
dd[:n, 0] = f

for j in range(1, n):
    for i in range(n - j):
        dd[i][j] = (dd[i+1][j-1] - dd[i][j-1]) / (x[i+j] - x[i])

x.append(2.0)
dd[n][0] = 2.90

for j in range(1, n + 1):
    i = n - j
    dd[i][j] = (dd[i+1][j-1] - dd[i][j-1]) / (x[i+j] - x[i])

coeffs = dd[0, :]

x_eval = 2.5
p_val = newton_eval(x, coeffs, x_eval)

print(p_val)

2.127619047619047


task2

In [ ]:
#task2
def f_func(x):
    return 5*x**6 - x**5 + 7*x**4 + 3.75*x**3 - 2*x**2 + 1.5*x + 15

def derivative(x):
    return 30*x**5 - 5*x**4 + 28*x**3 + 11.25*x**2 - 4*x + 1.5

x0 = 1.0
h = 0.4

D_h = (f_func(x0+h) - f_func(x0)) / h
D_h3 = (f_func(x0+h/3) - f_func(x0)) / (h/3)

D_richardson = (3*D_h3 - D_h) / 2
D_backward = (f_func(x0) - f_func(x0-h)) / h

true_deriv = derivative(x0)

error_richardson = abs(D_richardson-true_deriv)
error_backward = abs(D_backward-true_deriv)

print(f"{D_richardson:.2f}")
print(error_richardson)
print(error_backward)

52.68
9.0662913580247
31.256800000000002


task3

In [ ]:
#task3
nodes = [(1, 2), (3, 5), (4, 8)]
x_vals = [p[0] for p in nodes]
y_vals = [p[1] for p in nodes]

n_nodes = len(x_vals)

x_reversed = list(reversed(x_vals))
y_reversed = list(reversed(y_vals))

max_power = 2*(n_nodes-1)
powers = list(range(max_power,-1,-2))

rows=[]
for xi in x_reversed:
    row=[]
    for p in powers:
        row.append(xi**p)
    rows.append(row)

X = np.array(rows,dtype=float)
y = np.array(y_reversed,dtype=float)

print(X)
print(y)

a = np.linalg.solve(X,y)

print(f"{a}")

[[256.  16.   1.]
 [ 81.   9.   1.]
 [  1.   1.   1.]]
[8. 5. 2.]
[0.00357143 0.33928571 1.65714286]
